swagger: "2.0"
info:
  description: "Used to search for possible datasets."
  version: "v0.1.0"
  title: "Search for a dataset"
  license:
    name: "Open Government Licence v3.0"
    url: "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
basePath: "/v1"
tags:
- name: "Public"
schemes:
- "https"
parameters:
  postcode:
    name: postcode
    description: "The 6 or 7 digit code that defines a postcode"
    in: path
    required: true
    type: string
  distance:
    name: distance
    description: "The radial distance from post code. The value should contain a numerical (float) value followed by the unit of measurement separated by a comma (e.g. 10,km). Acceptable units are: 1) km, kilometers, kilometres (case insensitive) 2) m, miles (case insensitive)"
    in: query
    required: true
    type: string
  limit:
    name: limit
    description: "The number of items requested, defaulted to 50 and limited to 1000."
    in: query
    type: integer
  offset:
    name: offset
    description: "The first row of resources to retrieve, starting at 0. Use this parameter as a pagination mechanism along with the limit parameter."
    in: query
    type: integer
paths:
  /search/postcodes/{postcode}:
    get:
      tags:
      - "Public"
      summary: "Search for an option within a hierarchical dimension"
      description: "Perform a search on dimension options which are within a hierarchy of a published version of a dataset by the ONS."
      parameters:
      - $ref: '#/parameters/postcode'
      - $ref: '#/parameters/distance'
      - $ref: '#/parameters/limit'
      - $ref: '#/parameters/offset'
      produces:
      - "application/json"
      responses:
        200:
          description: "A json list containing search results of datasets which intersect the area generated by the postcode and distance query parameter"
          schema:
            $ref: '#/definitions/Datasets'
        400:
          $ref: '#/responses/InvalidRequestError'
        404:
          $ref: '#/responses/NotFoundError'
        500:
          $ref: '#/responses/InternalError'
responses:
  InvalidRequestError:
    description: "Failed to process the request due to invalid request."
  InternalError:
    description: "Failed to process the request due to an internal error."
  NotFoundError:
    description: "Dimension or option not found."
definitions:
  Datasets:
    description: "The resulting resource of the completed search against a dimension hierarchy."
    type: object
    required: ["count","limit", "items", "offset"]
    properties:
      count:
        description: "The number of items returned."
        type: integer
      items:
        description: "The results of the postcode search."
        type: array
        items:
          $ref: '#/definitions/SearchResponse'
      limit:
        description: "The number of items requested, defaulted to 50 and limited to 1000."
        type: integer
      offset:
        description: "The first row of items to retrieve, starting at 0. Use this parameter as a pagination mechanism along with the limit parameter. The total number of items that one can page through is limited to 1000 items."
        type: integer
  SearchResponse:
    description: "An individual result (dataset) of the postcode search"
    type: object
    required: ["name", "location"]
    properties:
      name:
        type: string
        description: "The name of the geographical location of the dataset."
        example: "Wales"
      location:
        $ref: '#/definitions/Location'
  Location:
    description: "The geographical location of the dataset or data found, containing a geographial description of the shape."
    type: object
    required: [coordinates, type]
    properties:
      coordinates:
        description: "A set of list coordinates to handle different geographical shapes, e.g. ring, circle."
        type: array
        items:
          $ref: '#/definitions/Shape'
      type:
        description: "The type of shape of the geographical boundary."
        type: string
        enum: [
          "Polygon"
        ]
  Shape:
    description: "The actual shape of the geographical area the dataset belongs to."
    type: array
    items:
      $ref: '#/definitions/Coordinates'
  Coordinates:
    description: "A list of coordinates to generate a continuous boundary line, first and last item must match."
    type: array
    items:
      $ref: '#/definitions/Coordinate'
  Coordinate:
    description: "A single set of coordinates defining a single point on the Earth by longitude then latitude respectively. Numerical values are float64 type."
    type: number
    example: [ -3.4627, 51.486 ] 
